# Generated by Django 3.0.2 on 2020-03-02 17:22

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(blank=True, choices=[('Arangu', 'Arangu'), ('Inter', 'Inter')], max_length=10)),
                ('sg', models.CharField(blank=True, choices=[('Single', 'Single'), ('Group', 'Group')], max_length=10, verbose_name='Single/Group')),
                ('duration', models.CharField(max_length=50, null=True)),
                ('nop', models.IntegerField(blank=True, default=1, verbose_name='Number of Participants')),
                ('slug', models.SlugField(default='slug', max_length=200, unique=True)),
                ('brief', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField()),
                ('rules', models.CharField(blank=True, max_length=500)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('venue', models.CharField(blank=True, max_length=250)),
                ('url', models.URLField(blank=True, default='url', verbose_name='Registration Link')),
                ('fees', models.IntegerField()),
                ('prize', models.CharField(max_length=200)),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to='post_images', verbose_name='Image')),
                ('minreg', models.IntegerField(default=15, verbose_name='Minimum Registrations')),
            ],
        ),
    ]
