# Generated by Django 3.0.2 on 2020-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='brief',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, default='5mins', max_length=50),
        ),
    ]
