# Generated by Django 3.0.2 on 2020-03-01 21:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='post_images', verbose_name='Image'),
        ),
    ]
