# Generated by Django 3.0.2 on 2020-03-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200302_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='brief',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True),
        ),
    ]
