# Generated by Django 3.0.2 on 2020-02-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200122_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
    ]
