# Generated by Django 3.0.2 on 2020-02-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200203_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(default='url'),
        ),
    ]
