# Generated by Django 3.0.2 on 2020-03-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200302_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
