# Generated by Django 3.0.2 on 2020-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200203_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brief',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(0, 'Arangu'), (1, 'Inter')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='nop',
            field=models.CharField(choices=[(0, 'Single'), (1, 'Team')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
