# Generated by Django 3.0.2 on 2020-02-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200205_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[(0, 'Arangu'), (1, 'Inter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='nop',
            field=models.CharField(blank=True, choices=[(0, 'Single'), (1, 'Team')], max_length=10),
        ),
    ]
