# Generated by Django 3.0.2 on 2020-02-05 17:12

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200205_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Arangu', 'Arangu'), ('Inter', 'Inter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='nop',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Team', 'Team')], max_length=10),
        ),
    ]
