# Generated by Django 3.0.2 on 2020-02-05 17:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200205_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='White_full.png', upload_to='post_images', verbose_name='Thumbnail'),
        ),
    ]
