# Generated by Django 3.0.2 on 2020-02-05 19:11

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200205_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='minreg',
            field=models.IntegerField(default=10, verbose_name='Minimum Registrations'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='White_full.jpg', upload_to='post_images', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nop',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Group', 'Group')], max_length=10, verbose_name='Single/Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(default='url', verbose_name='Registration Link'),
        ),
    ]
