# Generated by Django 3.0.2 on 2020-02-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200206_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated_by',
        ),
    ]
