# Generated by Django 3.0.2 on 2020-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sg',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Group', 'Group')], max_length=10, verbose_name='Single/Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nop',
            field=models.IntegerField(default=1, verbose_name='Number of Participants'),
        ),
    ]
