# Generated by Django 3.0.2 on 2020-02-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200206_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sg',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(default='5 min', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='minreg',
            field=models.IntegerField(default=15, verbose_name='Minimum Registrations'),
        ),
    ]
