# Generated by Django 3.0.2 on 2020-02-06 16:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='sanskriti2020.jpg', upload_to='post_images', verbose_name='Thumbnail'),
        ),
    ]
