# Generated by Django 3.0.2 on 2020-02-06 16:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200206_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='White_full.jpeg', upload_to='post_images', verbose_name='Thumbnail'),
        ),
    ]
