# Generated by Django 3.0.2 on 2020-02-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20200206_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='img',
        ),
    ]
