# Generated by Django 3.0.2 on 2020-02-06 19:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20200207_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='post_images', verbose_name='Thumbnail'),
        ),
    ]
