# Generated by Django 3.0.2 on 2020-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200207_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sg',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Group', 'Group')], max_length=10, verbose_name='Single/Group'),
        ),
    ]
