# Generated by Django 3.0.2 on 2020-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_event_sg'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='slug', editable=False, max_length=200),
        ),
    ]
